packages:
  - packages/*
  - apps/*
catalog:
  "@biomejs/biome": ^1.9.2
  "@fastify/deepmerge": ^2.0.0
  "@mantine/core": ^7.13.0
  "@mantine/hooks": ^7.13.0
  "@mdx-js/loader": ^3.0.1
  "@mdx-js/react": ^3.0.1
  "@next/mdx": ^14.2.13
  "@tabler/icons-react": ^3.18.0
  "@types/mdx": ^2.0.13
  "@types/node": ^22.7.3
  "@types/react": ^18.3.9
  autoprefixer: ^10.4.20
  bumpp: ^9.5.2
  clsx: ^2.1.1
  next: ^14.2.13
  next-transpile-modules: ^10.0.1
  postcss: ^8.4.47
  postcss-import: ^16.1.0
  postcss-preset-mantine: ^1.17.0
  postcss-simple-vars: ^7.0.1
  react: ^18.3.1
  react-dom: ^18.3.1
  rehype-mdx-code-props: ^3.0.1
  shikiji: ^0.10.2
  simple-git-hooks: ^2.11.1
  tailwindcss: ^3.4.13
  tailwind-preset-mantine: ^1.0.4
  tsup: ^8.3.0
  typescript: ^5.6.2
